cygnus-ngsi.sources = http-source
cygnus-ngsi.channels = mem-channel
cygnus-ngsi.sinks = pg-sink

# SOURCE
cygnus-ngsi.sources.http-source.type = org.apache.flume.source.http.HTTPSource
cygnus-ngsi.sources.http-source.port = 5055
cygnus-ngsi.sources.http-source.handler = com.telefonica.iot.cygnus.handlers.NGSIRestHandler
cygnus-ngsi.sources.http-source.handler.notification_target = /notify
cygnus-ngsi.sources.http-source.handler.default_service = openiot
cygnus-ngsi.sources.http-source.handler.default_service_path = /

# CHANNEL (buffer em memória) - aumenta capacidade e transações
cygnus-ngsi.channels.mem-channel.type = memory
cygnus-ngsi.channels.mem-channel.capacity = 200000
cygnus-ngsi.channels.mem-channel.transactionCapacity = 5000

# SINK PostgreSQL
cygnus-ngsi.sinks.pg-sink.type = com.telefonica.iot.cygnus.sinks.NGSIPostgreSQLSink
cygnus-ngsi.sinks.pg-sink.channel = mem-channel

cygnus-ngsi.sinks.pg-sink.postgresql_host = postgres-db
cygnus-ngsi.sinks.pg-sink.postgresql_port = 5432
cygnus-ngsi.sinks.pg-sink.postgresql_username = postgres
cygnus-ngsi.sinks.pg-sink.postgresql_password = password
cygnus-ngsi.sinks.pg-sink.postgresql_database = postgres
cygnus-ngsi.sinks.pg-sink.enable_cache = true

# ingestão em lote (muito importante)
cygnus-ngsi.sinks.pg-sink.batch_size = 2000
cygnus-ngsi.sinks.pg-sink.batch_timeout = 30

# Wire
cygnus-ngsi.sources.http-source.channels = mem-channel
