version: "3.7"
services:

  mongodb:
    image: mongo:4.4
    hostname: mongodb
    ports:
      - "27017:27017"
    networks:
      - LoRaWAN

  orion:
    image: fiware/orion:latest
    ports:
      - "1026:1026"
    command: -dbURI mongodb://mongodb:27017 -logLevel DEBUG -noCache INFO -logForHumans
    hostname: orion
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:1026/version"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - LoRaWAN

networks:
  LoRaWAN: {}
